# 3 - Using libraries

A (software) library is a collection of files (called modules) that contains functions for use by other programs.

Most of the power of Python is in the excellent libraries that can be found for free online, and that have already implemented many of the important algorithms/functions you will need during this Diploma.


# How do I install a library

If not already present, a library can be installed in several ways. A simple one is to use the `pip` installer, which can be called in terminal or even in a jupyter cell.

Let us see how we would install the library `numpy`.
(In this case, it will be already installed).



In [ ]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy

To import a library as a whole, we use the command `import`. Even if the library is installed, before we import it we cannot use it.



In [ ]:
import numpy

To learn the contents, we can use the `help` function

In [ ]:
help(numpy)

When we import the whole library, to use its modules and functions, we must call them with the prefix. Let us try and call the function `zeros(2)` which returns an array of 2 zeros.

In [ ]:
zeros(2)

In [ ]:
numpy.zeros(2)

To import only selected items from a library, we can use:
```
from ... import ...
```
Then we do not need to use prefix.

In [ ]:
from numpy import zeros
zeros(2)



We can also change the prefix. Conventionally, `numpy` is called `np`

In [ ]:
import numpy as np

np.zeros(2)

array([0., 0.])

# 3 - Numpy

**Summary**

> *   What is a numpy array (`array`)
>> * Construction (`zeros`, `ones`, `arange`, `linspace`)
>> * Array shape (`shape`)
>> * Indexing and slicing
> * Operations with arrays
>> * Arithmentic operations (`dot`)
>> * Universal functions (`sin`, `exp`, `sqrt`)
>> * Operations among the array elements (`sum`, `min`, `mean`, `std`)
> * Manipulating arrays
>> * Changing the shape of an array (`reshape`)
>> * Append (`append`)
>> * Stacking together different arrays (`hstack`, `vstack`, `empty`)
> * Random functions
>> * Generating random data (`random.rand`, `random.randint`, `random.normal`, `random.poisson`)
>> * Sampling (`random.shuffle`, `random.choice`)
> * Why numpy instead of Python lists?







For a more detailed tutorial see: https://numpy.org/devdocs/user/quickstart.html

Official reference: https://docs.scipy.org/doc/numpy-1.16.0/reference/index.html

## What is a numpy array

Numpy is the core module for scientific computing. It manages **homogeneous multidimensional array** (homogeneous means that one array must contain only one type of variable, differetly from Python lists). Basically numpy arrays can do super fancy mathematical things with vector, matrices, and, in general, multi-dimensional objects.

The module must be imported with the following command:


In [ ]:
import numpy as np
# the "as" statement specifies the local label referring to numpy.
# The usual convention is to use "np", but you can choose whatever name you want..

### Construction

Numpy arrays can be created from lists as follow:


In [ ]:
a1 = np.array([1,2,3,4,5])  # 1-d array from 1-d list
print(a1)

a2 = np.array([[1,2],[3,4]])  # 2-d array from a nested list
print(a2)

There exists several constructors for every need:

In [ ]:
a = np.zeros((2,5))  # Array of zeros. The argument specifies the size of each dimension.
print("zeors\n", a)

a = np.ones((4,3))  # Array of ones.
print("ones\n", a)

a = np.arange(2, 10, 2)  # Sequence of numbers (start included, stop excluded, step).
print("arange\n", a)

a = np.linspace(1, 30, 6)  # Sequence of numbers evenly spaced (start included, stop included, number of points).
print("linspace\n", a)

### Array shape

The array dimensions can be obtained with the `shape` property. In NumPy dimensions are called *axes*.

In [ ]:
a = np.zeros(5)  # 1-d vector
print(a.shape)

a = np.zeros((3,2,4))  # 3-d vector
print(a.shape)
print(len(a))  # The len function reads only the number of elements in the first dimension/axis

### Indexing and slicing

An array can be red through indexing and slicing almost as a list

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Complete matrix\n", m)

print("Getting one row\n", m[2])

print("Getting one element\n", m[2][2], m[2,2])  # Numpy can read the next dimension after a comma (in lists this is not possible)

print("Slicing a sub-matrix\n", m[1:,1:])  # One can slice different dimensions at the same time

print("Getting a column\n", m[:,0])  # In this way you can select one column

A useful feature of numpy arrays are *boolean masks*, that are arrays of booleans of the same shape of a given array, say `a`. If `a` is indexed through the mask, only the elements corresponding to the position of the `True` elements are returned (in a new array).

In [ ]:
a = np.arange(10)
print("Original array\n",a)

mask = a > 5
print("Mask for the elements greater than 5\n",mask)

print("Masked array\n",a[mask])

Boolean masks are extremely useful to avoid loops (in which a given property is checked for all the array elements) and save computational time. In this respect, see le last part of this tutorial.

## Operations with arrays

### Arithmentic operations

Arithmetic operators on arrays apply elementwise.

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print("a: ", a, "b: ", b)
print()

print("a - b:",  a-b)

print("a * b:",  a*b)  # Elementwise, not a scalar product!

print("b ^ 2: ", b**2)

print("is a < 35? ", a<35)  # Also boolean operations cen be applied elementwise

a:  [20 30 40 50] b:  [0 1 2 3]

a - b: [20 29 38 47]
a * b: [  0  30  80 150]
b ^ 2:  [0 1 4 9]
is a < 35?  [ True  True False False]


Scalar product between two vectors using the method `dot()` or the symbol `@`.

A @ B:
$$
A \cdot B = \sum_{i} A_{i} B_{i}  
$$

(Note that `dot()` between 2D arrays (matrices) makes matrix multiplications! But using `matmul()` should be preffered instead )


In [ ]:
A = np.array([1,2,4,5])

B = np.array([3,4,1,-2])

print(A.dot(B))  # scalar product
print(A @ B)  # scalar product - equivalent command

5
5


In [ ]:
print("sin(a):", np.sin(b))

print("exp(a):", np.exp(b))

print("square-root(a):", np.sqrt(b))

sin(a): [0.         0.84147098 0.90929743 0.14112001]
exp(a): [ 1.          2.71828183  7.3890561  20.08553692]
square-root(a): [0.         1.         1.41421356 1.73205081]


### Operations among the array elements

Some examples of operation involving the array elements. See the documentation for more details and other examples.

In [ ]:
print(a.sum())  # Sum of all the array elements

print(a.min())  # Minimum

print(a.mean())  # Average value

print(a.std())  # Standard deviation

The argument axis in the numpy functions specifies the dimension at which the operation is applied.

In [ ]:
print(m)

print(m.sum(axis=0))  # Summing the elements in each column (across the first dimension)

print(m.sum(axis=1))  # Summing the elements in each row

## Matrix multiplications

Numpy has fast and reliable functions to deal with matrix operations, such as inversion or matrix multiplication.

In [ ]:
A = np.array([[1,2,6],[2,3,0],[6,0,-3]])
B = np.array([[-3,4,3],[2,-2,1],[0,2,1]])

C = np.matmul(A, B)

## note that there is a common shortwriting in @

D = A @ B

print( " C and D are equivalent? ", (C == D).all())


Remember that matrix multiplication is different from element-wise multiplication!

In [ ]:
C = np.matmul(A, B)
D = A * B

print( " C and D are equivalent? ", (C == D).all())

With numpy functions we can efficiently solve - for example - least square minimization.
Consider the case where we have a linear relation between some $X$ and $Y$ values, such as $Y=\beta_0 + \beta_1 X +\epsilon$, with $\epsilon$ some small error.

If we have a list of values $\{y_0, y_1, y_2, \dots, y_m\}$ and $\{x_0, x_1, x_2, \dots, x_m\}$, the solution for the $\hat{\beta}_0$ and $\hat{\beta}_1$ which minimize the squared error can be solved using linear algebra.

In [ ]:
X = np.linspace(-50,50, num=100) # constructs 100 values for x between -50 and 50
Y = X * 0.35 + 12 + (np.random.rand(100)-0.5) # constructs the Ys using beta_0 = 12 and beta_1 = 0.35

The solution can be found constructing an auxiliary vector that has at each row $(1, x_i)$ (this is due to the presence of the $\beta_0$).
Then, the solution for $\beta = (\beta_0, \beta_1)$ is:

$$
\beta = ( \tilde{X}^T \tilde{X})^{-1} \tilde{X}^T Y
$$

Where $()^{-1}$ indicates the matrix inverse `np.linalg.inv` and $^T$ indicates the matrix transpose  `array.T`

In [ ]:
Xt = np.vstack([np.ones(len(X)), X]).T
Y = Y.reshape(-1,1)

beta = np.linalg.inv(Xt.T @ Xt) @ Xt.T @ Y

print("beta_0 is ", beta[0], " and beta_1 ", beta[1])


## Outer products

The `outer` product between two arrays $A$ and $B$ produces a 2D array containing all the products between each element of A and each element of B.

$$
\text{outer}_{i,j} = A_i * B_j
$$

The arrays A,B are flatten to 1D if they were multidimensional.

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([1,-1,2,-2])

C = np.outer(A,B)
print(C)

[[ 1 -1  2 -2]
 [ 2 -2  4 -4]
 [ 3 -3  6 -6]
 [ 4 -4  8 -8]]


## Einstein sums

The 'Einstein's sum' is "a notational convention that implies summation over a set of indexed terms in a formula, thus achieving brevity." In it, it is assumed that summations is implied for each repeated indiced, without the need to use $\sum$ symbols.

$$
x_i y^i = \sum_i x_i y_i
$$

Note that there could be un-repeated indices, which would not be summed over. E.g.,

$$
x_{j i} y^i = \sum_i x_{ji} y_i
$$


The numpy function `einsum` is a very powerful function which allows to sum over sets of indices, while leaving others untouched. It uses a string as input with `ijk, ijm -> km` the indixes of the inputs left and the remaining indices right.

In [ ]:
# A with index      i j  k
A = np.random.rand( 5,3, 4) # note the shape (5,3,4)

# B with index      m  j  i
B = np.random.rand( 7, 3, 5) # note the shape (7,3,4)

# C summing over indixes i,j leaving untouched k,m
C = np.einsum( " ijk, mji-> km", A, B)
print(C, "\nC shape is ", C.shape)

# D summing over indixes i,j leaving untouched *m,k* in different order
D = np.einsum( " ijk, mji-> mk", A, B)
print(D, "\nD shape is ", D.shape)


# E summing over index i only, leaving untouched all other (I need to change names to the other j index)
E = np.einsum( " ijk, mLi-> mjkL", A, B)
print("\nE shape is ", E.shape)

[[3.23004811 4.39400887 3.58077694 3.94087239 3.61143709 4.2053059
  2.59529369]
 [3.61839947 4.08348989 3.90883708 4.99667168 3.95447623 4.04261279
  2.98183774]
 [2.74519433 2.85796763 2.92208011 2.98191051 3.02209    3.56282771
  2.69831496]
 [3.60492053 4.39272062 4.4208666  5.05872621 4.70117404 4.89878103
  3.53502529]] 
C shape is  (4, 7)
[[3.23004811 3.61839947 2.74519433 3.60492053]
 [4.39400887 4.08348989 2.85796763 4.39272062]
 [3.58077694 3.90883708 2.92208011 4.4208666 ]
 [3.94087239 4.99667168 2.98191051 5.05872621]
 [3.61143709 3.95447623 3.02209    4.70117404]
 [4.2053059  4.04261279 3.56282771 4.89878103]
 [2.59529369 2.98183774 2.69831496 3.53502529]] 
D shape is  (7, 4)

E shape is  (7, 3, 4, 3)


## Eigenvalues analysis

Numpy has many algebra modules which can deal with diagonalizations.
`numpy.linalg.eig` computes the eigenvalues and (right) eigenvectors of a square array. It takes the matrix as input and returns a tuple with eigenvalues and eigenvectors.


In [ ]:
A = np.array([[1,2,6],[2,3,0],[6,0,-3]])

eig_val, eig_vec = np.linalg.eig(A)
print('eigenvalues: \n', eig_val)
print('eigenvectors: \n', eig_vec)


## Manipulating arrays

Here we show some function to modify arrays and their shape. As for all the other examples in this tutorial, here we show just a small fraction of the wide range of possibilities that Numpy proposes.

### Changing the shape of an array

`reshape` function.
Be careful on the order of reshaping: There are two conventions available $'C'$-like (default) and $'F'$-like, standing for the languages C and Fortran.

With $'C'$ the "fastest" index is the last one, while with $F$ it is the first one.

In [ ]:
a = np.arange(12)  # Generating a 1-d array with 12 elements
print("Original array:\n", a)

print("Reshaped as a matrix:\n", a.reshape((3,4)))  # Be careful, the number of elements must be the same! You cannot reshape it in a 4x4 matrix

print("\n\nC-like reshaping.")
print("Reshaped as a 3-d array:\n", a.reshape((3,2,2)))
print("Fast-index is last:\n", a.reshape((3,2,2))[0,0,:])

print("\n\nF-like reshaping.")
print("Reshaped as a 3-d array:\n", a.reshape((3,2,2), order='F'))
print("Fast-index is first:\n", a.reshape((3,2,2), order='F')[:,0,0])

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped as a matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


C-like reshaping.
Reshaped as a 3-d array:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Fast-index is last:
 [0 1]


F-like reshaping.
Reshaped as a 3-d array:
 [[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
Fast-index is first:
 [0 1 2]


Transposing

In [ ]:
m = a.reshape((4,3))
print("A matrix\n", m)
print("and its transpose\n", m.T)

### Append

The function `append` of numpy is slightly different from the `append` for lists.

In [ ]:
a = np.array([])  # An empty array
for i in range(10):
  a = np.append(a, i**2)  # Appending a single element at the array end

print(a)


a = np.array([])
for i in range(10):
  a = np.append(a, [1,0])  # Appending another array/list

print(a)


### Stacking together different arrays

In [ ]:
a = np.zeros((2,2))
b = np.ones((2,2))
print ("a:\n", a, "\nb\n", b)

print("vertical stack\n", np.vstack((a,b)))
print("horizontal stack\n", np.hstack((a,b)))

To dynamically generate a matrix row by row use vstack. Note that you need to initialize an empty array with the correct dimension.

In [ ]:
a = np.empty((0,2))  # To initialize an array
for i in range(5):
  a = np.vstack((a, [1,0]))
print (a)

### Broadcasting rules

When doing operations between arrays of different dimensions, Numpy generally assumes the expected behavior from the shapes.  
For example, a scalar multiplied by a vector returns each element of the vector multiplied by the scalar.

$$
a * (b_1, b_2, b_3) = (a*b_1, a*b_2, a*b_3)
$$


In [ ]:
a=3
b=np.array([1,-2,0])
print(a*b)

Sometimes, however, we need to force the "broadcasting" of the arrays.
To add an empty dimension to the array, we need to use the `None` keyword.
For example, let's assume that we want to achieve this result.

$$
(a_1, a_2, ..., a_n)^T * (b_1, b_2, ..., b_m) =  
\begin{pmatrix}
a_1b_1 & a_1b_2 & \cdots & a_1b_m \\
a_2b_1 & a_2b_2 & \cdots & a_2b_m \\
\vdots  & \vdots  & \ddots & \vdots  \\
a_nb_1 & a_nb_2 & \cdots & a_nb_m
\end{pmatrix}
$$
The naive way does not work:

In [ ]:
a = np.array([1,2,3])
b = np.array([-1,1])
print(a*b)

In [ ]:
a = np.array([1,2,3])
b = np.array([-1,1])
print(a[:,None]*b[None,:])

Let us use broadcasting for calculating the "distance matrix" between each point of an array.

$$
A = (a_1, a_2, a_3, ..., a_n)
$$


$$ d  =
\begin{pmatrix}
(a_1 - a_1)^2 & (a_1 - a_2)^2 & \cdots & (a_1 - a_n)^2 \\
(a_2 - a_1)^2 & (a_2 - a_2)^2 & \cdots & (a_2 - a_n)^2 \\
\vdots  & \vdots  & \ddots & \vdots  \\
(a_n - a_1)^2 & (a_n - a_2)^2& \cdots & (a_n - a_n)^2
\end{pmatrix}
$$

In [ ]:
A = np.arange(5)

print('A: \n', A)

d = (A[:,None] - A[None,:] )**2

print('d: \n', d)

## Random functions

All the random functions in Numpy are contained in the sub-module `random`.

See: https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html

### Generating random data

In [ ]:
print(np.random.rand()) # A single rand number in [0,1)

r = np.random.rand(3,4)  # Generating random numbers uniformely in [0,1) with a given shape
print(r)

# Generating random integers. Arguments: start included, stop excluded, size.
r = np.random.randint(2,5,(3,4))
print(r)

Data can be generated also from specific distributions (here few examples)

In [ ]:
# From normal distribution. Args: mean, standard dev, size.
r = np.random.normal(1,2,(3,4))
print(r)

# From poisson distribution. Args: mean, size.
r = np.random.poisson(2,(3,4))
print(r)

### Sampling

Shuffling an array.

Equivalent to a sampling without replacement: at each time an array element is randomly exctracted, put in a new array, and removed from the original array

In [ ]:
a = [1, 1, 1, 1, 2, 2, 2, 3, 3, 4]
print(a)

np.random.shuffle(a)  # The method modifies the array in-place

print(a)

Sampling without replacement: at each time an array element is randomly exctracted and put in a new array

In [ ]:
new_a = np.random.choice(a, 15)  # Note that here the new array can be larger than the original
print (new_a)

# Exercises (optional)

1) One of the exercise of last time dealt with calculating the distance between two DNA strings using the fraction of equal characters.

Now, use the documentation in the module `numpy.char` https://numpy.org/doc/stable/reference/routines.char.html to see how one would write the distance between two strings in numpy.

In [ ]:
a = 'ACTGACACTCCAAAAGCTTCTGAATGCTCGCGGACCTGTGCATACTGCTATACCGCGTACGTGATCGCGCTCCGGCACACCAAATACGGACCGGACTAAAGTAGTGAACCACCAAACTATGTCTGACTTCCCCTGAACTTTGCAGTATGCGACTTACCTGCTCTTGAAGAAGATCTGAACTTACTGTTTAAAATTACCTGGGCCCCCTATGTAAGACATAGATCTAGCTCATCAAGAGTAATTCGAGCTAGCCGAGCCCCCGCTGACACAGTCTAATAGGCCTGTAGCGACCTTTAATTGCACGGCTGGCTACAGGTTAATGGCGTTGCTTTTCATCCAGGGGTATACGACGTAATGAAAGTTGTGATCCGATCTCAGAGTGTGCACAAGGGAAACCGTCTGACAAGTAAGCGGCCTCCTGTGTTGGGCCGAGTGGCAAGTCGTCGCTCATAGTTCCGTACCACAGGCAAATTGCAATAACAAATCCTAGCAGAAACTCCACGTTGGCGCAGACTTTCGGAAAAATAACCTTAATCGACATCGCTTATACCTCACAAGGCCGGATTAATTACAGCGTTCAACGTTCTGCATTGTCAGTCGCTGGTCACATAGTCTCGTCGCGAGGGTCATTCGGCGTTAGTGCTGAGGGAAACTATAGAAGATTTATACCTCGCTACGGTATGCTGATGGGTTATAGAAGGAACAGAACCATGCGCGGAACCGCCGGTGACTCCTGTGCTCGTGGGCACTCTATTATCTGTGTCTTGGAAGCATCTCTTATCTGATGGTTTCGCATGTTGTAGATACACAGTGTTTTCCGGTTCGTTTTATCCTGGCTATTGCTTTTTCCGTTGACATTCATTGACATCGTGATTGGCATAAGCGCTCATAGACGCTTCGTTTATCCCGTTACCACGCTTA'
a = np.array(list(a))
b = 'ACCGACACTCCAAAAACTTCTGAACACTTACGGACATGCGCATGCGACTAAACTGCGTACCTTAGCGTGCTTCGGCACACCATATATGGGACGGGCCATGGCGGGGCACCACCATACTACGTCAAACCTCCACTCATCCTCGCAGAATACAACTTACCGGCTTTTGAAAAAGACTTGTCCTTACTGTTTAGAATTACTTTGGCCCCCTACGTAAGACATAAACACGGATCACCAAAGGCAAATTGGGGGAGCTGACCTACCGCTGTCCCTATCTAACACACCTATAGCGACCTTTAGTTACACAGCAGGCTACGTAATAATGACGTGGCTTATCACCCAGGGTTATACGGCGTAATGCATACTGCAGCCCGATTTCGGAAAGTCCCCAAGGGAGACTGCCTCACAAGCAGTTTCCTTCCCGTATTGTACCAAGTGACAATTTGTCGCCTATCATTCCATATCCCAAATGGATTACGGTGACGGGTCCTGACAGAAGATTCACGCTGATATAAACTTTCGAAAAGGCCATGTTAACCAGCATCGCTTGTACCTCGTCAGACAGCACGAATCACAGTGTTCAATGTTCTGCAGTGTCGGATAATTTTCACTTAACCTAATTACGAAGGCTAGTCGGGATTAGTGCTGGGCGCAACTACAAAAGGCTGATACCTCGCTACGGTACGCTAGGTGGTTGCAGAAGGAGCAAATTGATTAACGATAGTTCCGGTGTCTCCTATATTCGTGAGCAGTCTGTCGTTTTCATCCTGGGAGTGTCTCTTATCTAGTAGCTTCGCATGTCGAAGGTACACAATGCTTTCCTGGTTAGACTATTCTGGCTATTGCTGTTTCCGTTAGTACCCGCTGACTTCGTAATTACCACAAACGTCCACAGACGTTTCGTCGATACCGTCATCACGCTTA'
b = np.array(list(b))

# Write the distance between a and b exploiting numpy functions

2) Create a Gaussian Random matrix of size 10x10.
A Gaussian Random matrix is a symmetric matrix that has the diagonal terms independent random normally distributed numbers with mean $0$ and, for example, standard deviation $1/\sqrt{2}$, and all other terms must be independent random normally distributed numbers with mean $0$ and standard deviation $1$.

(One way to ensure a matrix is symmetric is to use $A_{symm} = (A + A^T)/2$).

Then calculate the eigenvalues, and create an histogram of their modulus using `numpy.histogram` https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# Construct the matrix using numpy.random methods

# Compute the eigenvalues using numpy.linalg methods

# Compute the histogram using the numpy.histogram methods

3) Einstein Sums. One of the most compact (and possibly confusing) way of writing operation is the Einstein convention, where repeated indices imply summation, i.e. contraction on that index.

$$
A_i B^i = \sum_i A_i B_i
$$


This allows for a compact writing of complex summations, especially of matrices and higher dimensions tensors. Note that the final dimension of the object is dictated by the indices which are *not* summated over.

$$
A_{kni} B^{n}_{jo} C^{ji} = ?
$$



In [ ]:
import numpy as np

K = 10
N = 9
I = 7
O = 11
J = 8

A = np.random.rand( K,N,I )
B = np.random.rand( N,J,O )
C = np.random.rand( J,I )

# compute the above summation following the Einstein notation, and check whether the final shape is what you expect


(10, 11)


## Why numpy instead of Python lists?

The obvious fact is that in Numpy there are several built-in functions for whatever necessity of a scientist.



Moreover, using Numpy there is a relevant increase in the performance of your algorithm, especially when one has to deal with a large amount of numbers (https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists):

* Numpy arrays consume less memory than lists when stored.

* Using the bulit-in functions speeds up your program a lot (see below).


In [ ]:
def sum_without_numpy(a_list):
  counter = 0
  for element in a_list:
    counter += element
  return counter

def sum_with_numpy(a_list):
  return np.sum(a_list)

In [ ]:
import time

a_big_list = np.random.rand(1000000)

t0 = time.time()
result = sum_without_numpy(a_big_list)
python_time = time.time()-t0
print("Result ", result, " obtained in ", python_time)

t0 = time.time()
result = sum_with_numpy(a_big_list)
numpy_time = time.time()-t0
print("Result with numpy", result, " obtained in ", numpy_time)

print("Numpy is ", python_time / numpy_time, " times faster!")

In general, iterations slow down your code. A useful trick to avoid them is to use boolean masks. In this example the task is to select the number larger than 0.5 and compute the average of this items. This can be done by iterating over the list elements or using the mask.

In [ ]:
t0 = time.time()
count = 0
summation = 0
for elem in a_big_list:
  if elem > 0.5:
    count += 1
    summation += elem
python_time = time.time()-t0
print("Average of elements larger than 0.5 ", summation/count, " obtained in ", python_time)

t0 = time.time()
mask = a_big_list > 0.5
result = a_big_list[mask].mean()
numpy_time = time.time()-t0
print("Elements larger than 0.5 with boolean masks", result, " obtained in ", numpy_time)

print("Numpy is ", python_time / numpy_time, " times faster!")